// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg67RQ681G4UQDr7Geo6bq3aV0U9puUxs',
    appId: '1:10659567570:web:7ec27c8862f9474e5bda0b',
    messagingSenderId: '10659567570',
    projectId: 'legal-network-ad078',
    authDomain: 'legal-network-ad078.firebaseapp.com',
    storageBucket: 'legal-network-ad078.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9UOEg2-Egvrt8vUBE-1Q81TRrNS-EByA',
    appId: '1:10659567570:android:145f46bdf231908d5bda0b',
    messagingSenderId: '10659567570',
    projectId: 'legal-network-ad078',
    storageBucket: 'legal-network-ad078.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQB5xaUCS3Ld6p1sUnPx7l1ZPxVD6Fx3o',
    appId: '1:10659567570:ios:b370d6b03a3ff2a55bda0b',
    messagingSenderId: '10659567570',
    projectId: 'legal-network-ad078',
    storageBucket: 'legal-network-ad078.firebasestorage.app',
    iosBundleId: 'com.legalnetwork.leagel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQB5xaUCS3Ld6p1sUnPx7l1ZPxVD6Fx3o',
    appId: '1:10659567570:ios:6bdb21ecbfe3f5bc5bda0b',
    messagingSenderId: '10659567570',
    projectId: 'legal-network-ad078',
    storageBucket: 'legal-network-ad078.firebasestorage.app',
    iosBundleId: 'com.example.leagel1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAg67RQ681G4UQDr7Geo6bq3aV0U9puUxs',
    appId: '1:10659567570:web:026bcd4f25ebdc455bda0b',
    messagingSenderId: '10659567570',
    projectId: 'legal-network-ad078',
    authDomain: 'legal-network-ad078.firebaseapp.com',
    storageBucket: 'legal-network-ad078.firebasestorage.app',
  );
}
